# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Darken < Formula
  desc "darken — Darkish Factory orchestration substrate CLI"
  homepage "https://github.com/danmestas/darken"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/darken/releases/download/v0.1.1/darken_0.1.1_darwin_amd64.tar.gz"
      sha256 "010c3ae72df0eee3b9337b97ab8b506c50d35be77605d7d940e6efc1a8db8b22"

      define_method(:install) do
        bin.install "darken"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/darken/releases/download/v0.1.1/darken_0.1.1_darwin_arm64.tar.gz"
      sha256 "b8d8c992bdaeef3be49f2ea2ab60fde637ab35ddd75693e2dca43f17a85a21a4"

      define_method(:install) do
        bin.install "darken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/darken/releases/download/v0.1.1/darken_0.1.1_linux_amd64.tar.gz"
      sha256 "11b90ebf97fb3fb57ff0de390443c2b85e2d3ec1e57262627adedd34b1198109"
      define_method(:install) do
        bin.install "darken"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/darken/releases/download/v0.1.1/darken_0.1.1_linux_arm64.tar.gz"
      sha256 "dde98b27db73ed831c115fd5e7d24179af3959a0bcc9dbde08e217eb69434668"
      define_method(:install) do
        bin.install "darken"
      end
    end
  end

  test do
    system "#{bin}/darken", "version"
  end
end
