# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Darken < Formula
  desc "darken — Darkish Factory orchestration substrate CLI"
  homepage "https://github.com/danmestas/darken"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/darken/releases/download/v0.1.0/darken_0.1.0_darwin_amd64.tar.gz"
      sha256 "2ad382c43fa33bac2854dc6a548c699dd8c60154fb003a093285fef360d8e158"

      define_method(:install) do
        bin.install "darken"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/darken/releases/download/v0.1.0/darken_0.1.0_darwin_arm64.tar.gz"
      sha256 "2727531f2512965289dfa9e60232f45a0577c320381fdf8e131d110671de72fc"

      define_method(:install) do
        bin.install "darken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/darken/releases/download/v0.1.0/darken_0.1.0_linux_amd64.tar.gz"
      sha256 "3017756dfab1b7517daca37a00e949119c1bda7265ec704ed2d2ce092ed45bbe"
      define_method(:install) do
        bin.install "darken"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/darken/releases/download/v0.1.0/darken_0.1.0_linux_arm64.tar.gz"
      sha256 "83e7c5fabf1fb36e786882507fbb75031b4236584f9df8a7cd353046e9e4148e"
      define_method(:install) do
        bin.install "darken"
      end
    end
  end

  test do
    system "#{bin}/darken", "version"
  end
end
