# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bones < Formula
  desc "Unified CLI for the bones agent-infrastructure substrate (workspace, orchestrator, tasks)."
  homepage "https://github.com/danmestas/bones"
  version "0.15.4"
  license "Apache-2.0"

  depends_on "danmestas/tap/leaf" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/bones/releases/download/v0.15.4/bones_0.15.4_darwin_x86_64.tar.gz"
      sha256 "2718b9029058db153e7705767ae15778be74b4110d6b173958f9fbeb1952c057"

      define_method(:install) do
        bin.install "bones"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/bones/releases/download/v0.15.4/bones_0.15.4_darwin_arm64.tar.gz"
      sha256 "efe130c0ebef0c12500a31366f04bf3981bd2c4d3ee0e027c1db03d770ebcb00"

      define_method(:install) do
        bin.install "bones"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/bones/releases/download/v0.15.4/bones_0.15.4_linux_x86_64.tar.gz"
      sha256 "0f888425272e7ec3a531a4b06e808136b7af86ce477c04a6f721f26c2b8e5538"
      define_method(:install) do
        bin.install "bones"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/bones/releases/download/v0.15.4/bones_0.15.4_linux_arm64.tar.gz"
      sha256 "32943be350b79f7267365503af0e239eef1640248411f3916968a4d7c132a521"
      define_method(:install) do
        bin.install "bones"
      end
    end
  end

  test do
    system "#{bin}/bones --version"
  end
end
