# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bones < Formula
  desc "Unified CLI for the bones agent-infrastructure substrate (workspace, orchestrator, tasks)."
  homepage "https://github.com/danmestas/bones"
  version "0.16.0"
  license "Apache-2.0"

  depends_on "danmestas/tap/leaf" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/bones/releases/download/v0.16.0/bones_0.16.0_darwin_x86_64.tar.gz"
      sha256 "4969525ea41fce5d30ab9041b8d7c7f24628081cad192759598c213389283d18"

      define_method(:install) do
        bin.install "bones"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/bones/releases/download/v0.16.0/bones_0.16.0_darwin_arm64.tar.gz"
      sha256 "72d6d9c187476f4c02914dc2765f92acea2bb9b97946ea3b9407db2cb55c23e4"

      define_method(:install) do
        bin.install "bones"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/bones/releases/download/v0.16.0/bones_0.16.0_linux_x86_64.tar.gz"
      sha256 "cc4dabd17a1a3f60a00aa105a2b7114dc6fb328dc85f6c00711ffd50f3756d61"
      define_method(:install) do
        bin.install "bones"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/bones/releases/download/v0.16.0/bones_0.16.0_linux_arm64.tar.gz"
      sha256 "7543f5b084c5a7281b2e818af6643a9afe2d7b7f556b82d439ada9da34cb2b83"
      define_method(:install) do
        bin.install "bones"
      end
    end
  end

  test do
    system "#{bin}/bones --version"
  end
end
