# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Darken < Formula
  desc "darken — Darkish Factory orchestration substrate CLI"
  homepage "https://github.com/danmestas/darken"
  version "0.1.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/darken/releases/download/v0.1.19/darken_0.1.19_darwin_amd64.tar.gz"
      sha256 "d1a778d520d4292784579d8328f3c3cdc94269079cf57e29f84ebb1214de41ba"

      define_method(:install) do
        bin.install "darken"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/darken/releases/download/v0.1.19/darken_0.1.19_darwin_arm64.tar.gz"
      sha256 "018aeda650fccb7dc574de5799bbeac86b2cf5c6c75358b16d7e62a6bff55847"

      define_method(:install) do
        bin.install "darken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/darken/releases/download/v0.1.19/darken_0.1.19_linux_amd64.tar.gz"
      sha256 "1386c6b40934b17d091197bef6492dbe6afed82f1b576f8965dd1d09691f1eb3"
      define_method(:install) do
        bin.install "darken"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/darken/releases/download/v0.1.19/darken_0.1.19_linux_arm64.tar.gz"
      sha256 "8185a2207ca37216f98cf7a56eb146fdd6d78c4bf4e452ac8c8852af4724def6"
      define_method(:install) do
        bin.install "darken"
      end
    end
  end

  test do
    system "#{bin}/darken", "version"
  end
end
