# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Darken < Formula
  desc "darken — Darkish Factory orchestration substrate CLI"
  homepage "https://github.com/danmestas/darken"
  version "0.1.25"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/darken/releases/download/v0.1.25/darken_0.1.25_darwin_amd64.tar.gz"
      sha256 "7d2732307a61643af97683d1d9f867e89f32d25ba263b413dcd387572355e55b"

      define_method(:install) do
        bin.install "darken"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/darken/releases/download/v0.1.25/darken_0.1.25_darwin_arm64.tar.gz"
      sha256 "566732b4685276b3b558706e70294eec6a322be9001e93dd33d42fdfe170aac9"

      define_method(:install) do
        bin.install "darken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/darken/releases/download/v0.1.25/darken_0.1.25_linux_amd64.tar.gz"
      sha256 "fface7e2c3ed5835992e58c9b437c8e46cb8bcf6c7f35439b54975b65612a9a4"
      define_method(:install) do
        bin.install "darken"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/darken/releases/download/v0.1.25/darken_0.1.25_linux_arm64.tar.gz"
      sha256 "b0e7a2a39116bb5d327d40c85ed0a0cfc556a280492a3363aa7668a54d1b8d40"
      define_method(:install) do
        bin.install "darken"
      end
    end
  end

  test do
    system "#{bin}/darken", "version"
  end
end
