# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Darken < Formula
  desc "darken — Darkish Factory orchestration substrate CLI"
  homepage "https://github.com/danmestas/darken"
  version "0.1.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/darken/releases/download/v0.1.21/darken_0.1.21_darwin_amd64.tar.gz"
      sha256 "d25836ddbdb7222c783d3337eaf927bbed23af513b1945d5d6c1a662c72e82ed"

      define_method(:install) do
        bin.install "darken"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/darken/releases/download/v0.1.21/darken_0.1.21_darwin_arm64.tar.gz"
      sha256 "0c14a1e1c676a11f190814091227aa0c05dd235a05021d096699ed55b730a855"

      define_method(:install) do
        bin.install "darken"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/darken/releases/download/v0.1.21/darken_0.1.21_linux_amd64.tar.gz"
      sha256 "3be6021a9df5a773397bc37a46c2e996587df6a4be935d634405a10848527501"
      define_method(:install) do
        bin.install "darken"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/darken/releases/download/v0.1.21/darken_0.1.21_linux_arm64.tar.gz"
      sha256 "497fedcaa2f3604acbf59978b302c9337bc25fd001daf867951f756ad92bb779"
      define_method(:install) do
        bin.install "darken"
      end
    end
  end

  test do
    system "#{bin}/darken", "version"
  end
end
