# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edgesync < Formula
  desc "Sync engine for distributed teams: NATS messaging or peer-to-peer Fossil sync."
  homepage "https://github.com/danmestas/EdgeSync"
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.6/EdgeSync_0.0.6_darwin_x86_64.tar.gz"
      sha256 "54710baac2066d48bf8a7efa53700ade278fd6a0463581752c97ef5f799460fd"

      define_method(:install) do
        bin.install "edgesync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.6/EdgeSync_0.0.6_darwin_arm64.tar.gz"
      sha256 "96f99f96e1c071a57a4d11501f4f138407aee0fc9ffc92d454e95e3e6456af5a"

      define_method(:install) do
        bin.install "edgesync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.6/EdgeSync_0.0.6_linux_x86_64.tar.gz"
      sha256 "c49c8f0e850b683648a51e5f5996a5842b06d44f8b606dd32c595179b533a7dc"
      define_method(:install) do
        bin.install "edgesync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.6/EdgeSync_0.0.6_linux_arm64.tar.gz"
      sha256 "8e04d0444cdbb90decb579aaf8a1e5f3df5734e8eb20c69297bcdd9db97e6ef3"
      define_method(:install) do
        bin.install "edgesync"
      end
    end
  end

  test do
    system "#{bin}/edgesync --version"
  end
end
