# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leaf < Formula
  desc "Leaf daemon: bridges a workspace to a NATS+Fossil hub. Spawned by bones."
  homepage "https://github.com/danmestas/EdgeSync"
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.8/leaf_0.0.8_darwin_x86_64.tar.gz"
      sha256 "dbb87d598929825b3b381f394cd07cedb8b3dc89d38dba64a369fd6b44ed63c0"

      define_method(:install) do
        bin.install "leaf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.8/leaf_0.0.8_darwin_arm64.tar.gz"
      sha256 "c174dafb528a7e8342f8dfdcf163f565ac483685937ce271ffc1551f88ed0a49"

      define_method(:install) do
        bin.install "leaf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.8/leaf_0.0.8_linux_x86_64.tar.gz"
      sha256 "d58fa4429e1083d01b30c51acf158d759ceb51b826464158f7eb42b9cd7caec6"
      define_method(:install) do
        bin.install "leaf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.8/leaf_0.0.8_linux_arm64.tar.gz"
      sha256 "4c4f5e0534c7202541dea859ac658c453d0e8fa46576ab86b1a9abf49226247a"
      define_method(:install) do
        bin.install "leaf"
      end
    end
  end

  test do
    assert_match "Usage of", shell_output("#{bin}/leaf -h 2>&1")
  end
end
