# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leaf < Formula
  desc "Leaf daemon: bridges a workspace to a NATS+Fossil hub. Spawned by bones."
  homepage "https://github.com/danmestas/EdgeSync"
  version "0.0.10"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.10/leaf_0.0.10_darwin_x86_64.tar.gz"
      sha256 "a147bd61c75dac33cd5f283d14d612e20d8e22b4f87a13ca9fcc27f2d8503281"

      define_method(:install) do
        bin.install "leaf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.10/leaf_0.0.10_darwin_arm64.tar.gz"
      sha256 "d985f25f2d6a6d27b675543a6d705e6e38f85263e62ac5d0af4f5be685f29f32"

      define_method(:install) do
        bin.install "leaf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.10/leaf_0.0.10_linux_x86_64.tar.gz"
      sha256 "53145d7f725213078de582cf84a84e4654b62e8a036878413703b2373f65eae9"
      define_method(:install) do
        bin.install "leaf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.10/leaf_0.0.10_linux_arm64.tar.gz"
      sha256 "697058c23cb1313d227d69edb0d9e255b221e051f2f3d72ff31abacfc3b0dd29"
      define_method(:install) do
        bin.install "leaf"
      end
    end
  end

  test do
    assert_match "Usage of", shell_output("#{bin}/leaf -h 2>&1")
  end
end
