# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leaf < Formula
  desc "Leaf daemon: bridges a workspace to a NATS+Fossil hub. Spawned by bones."
  homepage "https://github.com/danmestas/EdgeSync"
  version "0.0.17"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.17/leaf_0.0.17_darwin_x86_64.tar.gz"
      sha256 "3f0d4891120e2afc27d5338564adb45254703361a110c20a9aa02d0496c64fab"

      define_method(:install) do
        bin.install "leaf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.17/leaf_0.0.17_darwin_arm64.tar.gz"
      sha256 "b6409c04d929dfb12105bb431c1bc346abe5e4e8fd950062725b7085fa081897"

      define_method(:install) do
        bin.install "leaf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.17/leaf_0.0.17_linux_x86_64.tar.gz"
      sha256 "5897144cf8959300038197644203b8f707028bcc262fc158689f5cec675b9ef9"
      define_method(:install) do
        bin.install "leaf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danmestas/EdgeSync/releases/download/v0.0.17/leaf_0.0.17_linux_arm64.tar.gz"
      sha256 "5afb84ec55a06ca084b07e90a7bb897ff6dbd2bef7635e3d444718a2be34d5fe"
      define_method(:install) do
        bin.install "leaf"
      end
    end
  end

  test do
    assert_match "Usage of", shell_output("#{bin}/leaf -h 2>&1")
  end
end
